os: linux
sudo: false
language: node_js
node_js:
  - "10"

install:
  - npm install

before_script:

script:
  - mocha ./test/start.js

after_script:

branches:
  only:
    - master
    - Dev

notifications:
  email: foreso@sina.com